### ISSUE TITLE
Embed use 

### ISSUE THREAD

**Issue by MikhailKlemin** [jlubawy/go-boilerpipe#11]
Hi There!
What would be best way to use it in the project where I have bunch of web pages in []byte form. 

Something like
```go
b, _ := boilerpipe.ExtractFromBytes([]byte{"Some single html page here"}) 
fmt.Println(b.Content)
```

I did some "cowboy shortcut" 

```go
func boiler(b []byte) string {
	r := bytes.NewReader(b)
	doc, err := boilerpipe.ParseDocument(r)
	if err != nil {
		log.Fatal(err)
	}
	boilerpipe.ArticlePipline.Process(doc)
	return doc.Content()
}
``` 
Works good so far:-)

**Comment by MikhailKlemin** [comment]
Hi! Sorry for late reply. The problem is the results are do not match results from actual boilerplate ie a lot of time it's empty :-(  Actually this is same with Goose port for Go. 
Very sad, because I have to use Tika, and that approach has a lot of issues with performance.

**Comment by jlubawy** [comment]
No worries. If you can send me an example of an article you are trying to process I can look into why the results are empty. I've made some changes from the original Java Boilerpipe to fix issues I've had with various websites, so it's possible I might have broken it for other sites.

If I can get it working I could also add it to the tests so it doesn't break again in the future.

**Comment by MikhailKlemin** [comment]
Hi there, take a look @facebook, 

[comparision.csv.zip](https://github.com/jlubawy/go-boilerpipe/files/2594120/comparision.csv.zip)

**Comment by jlubawy** [comment]
I don't know if this tool is going to be very good at extracting content from Facebook pages. It's meant more for articles on news websites such as nytimes.com or something similar.

That said, I ran an experiment with the CSV you provided and I think I got different results than you (see the last column): https://gist.github.com/jlubawy/fcfa0adf023ed8f2017d8f475b01cdd0#file-output-csv

Was the "Boilerpipe" column in the CSV you provided "go-boilerpipe" or the original Java version?

**Comment by MikhailKlemin** [comment]
Hi! That was boilerpipe response from [Tika Server 1.19 ](https://wiki.apache.org/tika/TikaJAXRS)

> Use the Boilerpipe handler (equivalent to tika-app's --text-main) with text output:
> `$ curl -T price.xls http://localhost:9998/tika/main --header "Accept: text/plain"`

**Comment by jlubawy** [comment]
So is the ```go-boilerpipe``` output good enough for your needs?

If not you might be able to create a new ```Pipeline``` that gives you better results. See ```ArticlePipeline``` as a starting point: https://godoc.org/github.com/jlubawy/go-boilerpipe#pkg-variables

**Comment by jlubawy** [comment]
I'm closing this issue, please let me know if you're still having any issues.
