### ISSUE TITLE
Is there no interfahtmlce for extracting HTML

### ISSUE THREAD

**Issue by jerry94test** [jlubawy/go-boilerpipe#13]
Is there no interface for extracting HTML,
I need to get html. Is there an excuse?

**Comment by jlubawy** [comment]
The library doesn't provide a method to download HTML from a website, but you can do something like this: https://github.com/jlubawy/go-boilerpipe/blob/master/cmd/boilerpipe/extract.go#L95

**Comment by jerry94test** [comment]
Thank you,

I have solved it.
