### ISSUE TITLE
Same Content but different Results

### ISSUE THREAD

**Issue by muhammet-mucahit** [jlubawy/go-boilerpipe#15]
[First](https://www.hepsiburada.com/huawei-p30-lite-128-gb-huawei-turkiye-garantili-p-HBV00000KJE2D?magaza=BittiBitiyor)
[Second](https://www.hepsiburada.com/samsung-galaxy-a50-2019-64-gb-samsung-turkiye-garantili-p-HBV00000IF4OW)

When I tested the code with these two url, I faced with a problem.
The problem is these two page contains same contents but the code returns different results.
I also tested with base boilerpipe library with Java and Python also but they produce correct results.

If you want me to share some images.. I can.

Thank you

**Comment by jlubawy** [comment]
Hi, thanks for reporting the issue.

Are you sure the pages have the same content? The links you provided are:
- https://www.hepsiburada.com/huawei-p30-lite-128-gb-huawei-turkiye-garantili-p-HBV00000KJE2D?magaza=BittiBitiyor
- https://www.hepsiburada.com/samsung-galaxy-a50-2019-64-gb-samsung-turkiye-garantili-p-HBV00000IF4OW

Just in the URLs it looks like one is for **huawei-p30-lite** and the other **samsung-galaxy-a50**. Searching for similar content in the pages I can't find any either.

**Comment by muhammet-mucahit** [comment]
No, I just mean the content structures of the pages are same not the content. Sorry for the mispresent.
