### ISSUE TITLE
go install github.com/... fails

### ISSUE THREAD

**Issue by BrianODell** [jlubawy/go-boilerpipe#2]
When I run this:
`$ go install github.com/jlubawy/go-boilerpipe/cmd/boilerpipe`

I get:
```
can't load package: package github.com/jlubawy/go-boilerpipe/cmd/boilerpipe: cannot find package "github.com/jlubawy/go-boilerpipe/cmd/boilerpipe" in any of:
        /usr/local/go/src/github.com/jlubawy/go-boilerpipe/cmd/boilerpipe (from $GOROOT)
        /Users/bodell/go/src/github.com/jlubawy/go-boilerpipe/cmd/boilerpipe (from $GOPATH)
```

I'm a Go newbie.  Maybe I need to do more to set it up on my machine?

**Comment by jlubawy** [comment]
It looks like you don't have the source downloaded to your ```$GOPATH``` which is why it says it can't find it.

I think you want to run ```go get -u github.com/jlubawy/go-boilerpipe/cmd/boilerpipe``` which will download, compile and install the command-line tool. You can also use ```go get -u github.com/jlubawy/go-boilerpipe/...``` to install the entire package.

**Comment by BrianODell** [comment]
Thanks! That worked.  If anyone else is a GO newbie reading this.  My binary was installed here: ~/go/bin/boilerpipe
