### ISSUE TITLE
go install http://github.com/jlubawy/go-boilerpipe/cmd/boilerpipe

### ISSUE THREAD

**Issue by hosseinmousavi** [jlubawy/go-boilerpipe#4]
can't load package: package http:/github.com/jlubawy/go-boilerpipe/cmd/boilerpipe: cannot find package "http:/github.com/jlubawy/go-boilerpipe/cmd/boilerpipe" in any of:

**Comment by jlubawy** [comment]
I think the README documentation was wrong, I updated it to ```go get -u github.com/jlubawy/go-boilerpipe/...``` which should solve your problem.
